services:
    nest_backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: backend
        restart: unless-stopped
        env_file:
          - .env
        ports:
          - "3000:3000"
        expose:
          - 3000

    next_frontend:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3030:3030"
    working_dir: /app

    postgres:
        image: postgres:17-alpine
        container_name: postgres
        restart: always
        ports:
          - ${POSTGRES_PORT}:${POSTGRES_PORT}
        env_file:
          - .env
        expose:
          - ${POSTGRES_PORT}
        command: -p ${POSTGRES_PORT}
        volumes:
          - /opt/postgresql/data:/var/lib/postgresql/data
