services:
  nest_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    expose:
      - 3000

  # nest_backend:
  #   image: back:prod
  #   container_name: backend
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   ports:
  #     - "3000:3000"

  # postgres:
  #   user: postgres
  #   image: postgres:17-alpine
  #   restart: always
  #   expose:
  #     - ${POSTGRES_PORT}
  #   command: -p ${POSTGRES_PORT}
  #   env_file:
  #     - .env
  #   ports:
  #     - ${POSTGRES_PORT}:${POSTGRES_PORT}
  #   volumes:
  #     - /opt/postgresql/data:/var/lib/postgresql/data
