services:
  prisma-migrate:
    container_name: prisma-migrate
    build:
      context: prisma
      dockerfile: Dockerfile
    env_file:
     - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env
    expose:
      - ${POSTGRES_PORT}
    command: -p ${POSTGRES_PORT}
    volumes:
      - /opt/postgresql/data:/var/lib/postgresql/data